# Generated by Django 3.2.12 on 2022-03-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_time', models.CharField(max_length=25)),
                ('running_time', models.CharField(max_length=15)),
                ('cpu_usage', models.IntegerField()),
                ('cpu_temperature', models.IntegerField()),
                ('memory_usage', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=15)),
                ('netmask', models.CharField(max_length=15)),
                ('default_gateway', models.CharField(max_length=15)),
            ],
        ),
    ]
