# Generated by Django 3.2.12 on 2022-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminf',
            name='output_address',
            field=models.CharField(default=' ', max_length=25),
        ),
    ]
