# Generated by Django 4.0.3 on 2022-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_systeminf_output_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminf',
            name='name_of_device',
            field=models.CharField(default=' ', max_length=25),
        ),
    ]
